import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function ChatPage() {
  const [isOpen, setIsOpen] = useState(false)

  const [last, setLastId] = useState('')

  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')



  const togglePopup = () => {
    setIsOpen(!isOpen)
  }

  function handleSubmit(event) {
    event.preventDefault()
    const date = new Date()
    const lastId = 'message:'+date.toString()
    const messageObject = {
      from: 1,
      to:   2,
      text: input,
      datetime: date,
      id: lastId,
      key: lastId
    }
    setLastId(lastId)
    setMessages([...messages, messageObject])
    setInput('')
  }

  return (
    <div className={styles.bgPicture}>
      <div className={styles.container}>
        <div className={styles.main}>
          <Head>
            <title>Pokélove</title>
            <meta name="description" content="Generated by a lot of redbull" />
            <link rel="icon" href="/logo.png" />
          </Head>
          <div style={{
            backgroundColor: 'blue',
            opacity: '80%',
            position: 'fixed',
            right:'0',
            bottom: '0',
            borderRadius: '10%',
            margin: '5vmin',
            minWidth: '20vmax', minHeight:'20vmin',
            borderTopLeftRadius:  '5vmin',
            borderTopRightRadius: '5vmin',
          }}>
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              flexDirection: 'row',
              backgroundColor: '#CC',
              padding: '1vmin',
              borderTopLeftRadius:  '5vmin',
              borderTopRightRadius: '5vmin',
            }}>
              <h2>Chat</h2>
              <div className={styles["popup-close-button"]} onClick={togglePopup}>
                &times;
              </div>
            </div>
            {isOpen && (
              <>
                <button onClick={() => {
                  const element = document.getElementById(last)
                  if (element) {
                    element.scrollTo({top: -10})
                  }
                }}>GoTOLast</button>
                <ul style={{
                  width: '20vmax', height:'20vmin',
                  wordWrap: 'break-word',
                  margin: '1vmin',
                  overflow: 'scroll'
                }}>
                  {messages.map((message) => (
                    <li id={message.id} key={message.key}>{message.text}</li>
                  ))}
                </ul>
                <form style={{
                  display: 'flex',
                  justifyContent: 'center',
                  flexDirection: 'row',
                  backgroundColor: 'yellow'
                }} onSubmit={handleSubmit}>
                  <input value={input} onChange={(event) => setInput(event.target.value)} />
                  <button type="submit">Send</button>
                </form>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
