import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.bgPicture}>
    <div className={styles.container}>
        <Head>
          <title>Pokélove</title>
          <meta name="description" content="Generated by a lot of redbull" />
          <link rel="icon" href="/logo.png" />
        </Head>

        <main className={styles.main}>

          <h1 className={styles.title}>
            Welcome to Pokélove
          </h1>

          <a href="./register" className={styles.card}>
            <h2>Inscription &rarr; </h2>
            <p>Discover and match moucho pokemon de ta région.</p>
          </a>

          <a href="./login" className={styles.card}>
            <h2>Déjà inscrit ?</h2>
            <p>Ce connecter &rarr; </p>
          </a>

        </main>
      </div>
    </div>
  )
}
