import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  if (typeof window !== "undefined"){
    return (
      <div className={styles.bgPicture}>
        <div className={styles.container} style={{opacity: '60%'}}>
          <Head>
            <title>Pokélove</title>
            <meta name="description" content="Generated by a lot of redbull" />
            <link rel="icon" href="/logo.png" />
          </Head>
          <main className={styles.main}>
            <h1 className={styles.title}>
              Welcome to Pokélove
            </h1>
            <div className={styles.grid}>
              <a href="./register" className={styles.card}>
                <h2>Inscription &rarr; </h2>
                <p>Match moucho pokemon de ta région</p>
              </a>
              <a href="./login" className={styles.card}>
                <h2>Déjà inscrit ?</h2>
                <p>Ce connecter &rarr; </p>
              </a>
            </div>
          </main>
        </div>
      </div>
    )
  } else {
    return null
  }
}
