import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Login() {
  const registerUser = async event => {
    event.preventDefault()

    const res = await fetch('/api/hello', {
      body: JSON.stringify({
        name: event.target.name.value,
        passWord: event.target.password.value
      }),
      headers: {
        'Content-Type': 'application/json'
      },
      method: 'POST'
    })

    const result = await res.json()
    console.log(result)
    // result.user => 'john Doe'
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokélove - register</title>
        <meta name="description" content="Generated by a lot of redbull" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Connexion
          Connexion
        </h1>

        <form onSubmit={registerUser}>
          
          Nom d'utilisateur
          <input id="name" name="name"
            type="text" autoComplete="name" required
          />
          <br/>
          Mot de passe
          <input id="password" name="password"
            type="password" autoComplete="mot de passe"
            required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
          />
          <br/>
          <button type="submit" className={styles.card}>Ce connecter</button>

        </form>

      </main>
    </div>
  )
}
