import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

let user

export default function Home() {
  if (typeof window === "undefined") {
    //bypass ssr
  } else {
    user = JSON.parse(localStorage.getItem("userInfo"))
    if (!user)
      console.log('tfw') // TODO fetch user
    else
      console.log(user)
  }
  let name = user.username
  return (
    <div className={styles.container} style={{}}>
        <Head>
          <title>Pokélove</title>
          <meta name="description" content="Generated by a lot of redbull" />
          <link rel="icon" href="/logo.png" />
        </Head>

        <mainDiv className={styles.main}>
          <div style={{
            border: 'solid',
            borderColor: 'white',
            backgroundColor: '#ffffff90',
            borderRadius: '2rem',
            display: 'flex',
            flexDirection: 'column',
            minHeight: '60vh',
            minWidth: '40vw',
            alignItems: 'center',
            justifyContent: 'space-evenly'
          }}>
            <div style={{
              fontSize: '5vh',
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
            }}>
              <img src='carapuce.jpeg' style={{
                borderRadius: '100vh',
                width: '20vh',
                marginRight: '15px',
                position: 'static',
                left: '30%',
              }}/>
              {name}
            </div>
            popularité
            <div style={{
              border: 'solid',
              borderColor: 'white',
              backgroundColor: '#ffffff90',
              borderRadius: '2rem',
              padding: '10px',
              inlineSize: '30vw',
              overflow: 'hidden',
            }}>
                alors bonjours je mappel Fabrice j'adore la pétanque et le jambon de bayonne
                alors bonjours je mappel Fabrice j'adore la pétanque et le jambon de bayonne
                alors bonjours je mappel Fabrice j'adore la pétanque et le jambon de bayonne
            </div>
            <div>
                info: sexe, level, types, cherche (male/female, level, type, race...), score popularité, date d'inscription
            </div>
            <div>
                tag
            </div>
          </div>
        </mainDiv>
      </div>
  )
}
