import Head from 'next/head'
import styles from '../styles/register.module.css'

async function getServerSideProps(context) {
  const body = {
    email: 'cyri',
    firstname: firstname,
    lastname: lastname,
    password: password
  }
  const headers = { 'Content-Type': 'application/json' }
  const res = await fetch(
    'http://127.0.0.1:5000/auth/register',
    { body, headers, method: 'POST' },
  )
  return {
    props: {}
  }
}

export default function Register() {
  const registerUser = async event => {
    event.preventDefault()
    const { email, firstname, lastname, password } = event.target
    const body = {
      email: email,
      firstname: firstname,
      lastname: lastname,
      password: password
    }
    console.log(body)
    const headers = { 'Content-Type': 'application/json' }
    const res = await fetch(
      'http://127.0.0.1:5000/auth/register',
      { body, headers, method: 'POST' },
    )
    console.log(await res.json())
  }
  return (
    <div className={styles.bgPicture}>
      <div className={styles.container}>login
        <Head>
          <title>Pokélove - register</title>
          <meta name="description" content="Generated by a lot of redbull" />
          <link rel="icon" href="/logo.png" />
        </Head>

        <main className={styles.main}>

          <h1 className={styles.title}>
            Crée un compte
          </h1>

          <form onSubmit={registerUser}>

          Email
          <input id="email" name="email"
            type="text" autoComplete="email" required
          />
          <br/>

          Prénom
          <input id="firstname" name="firstname"
            type="text" autoComplete="firstname" required
          />
          <br/>
          Nom de famille
          <input id="lastname" name="lastname"
            type="text" autoComplete="lastname" required
          />
          <br/>
          Mot de passe
          <input id="password" name="password"
            type="password" autoComplete="mot de passe"
            required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
          />
          <br/>
          <button type="submit" className={styles.card}>Ce connecter</button>

        </form>

          
          <a href="./login" className={styles.card}>
            <h2>Déjà inscrit ? &rarr;</h2>
            <p>Ce connecter</p>
          </a>

        </main>
      </div>
    </div>
  )
}
