import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Register() {
  return (
    <div className={styles.container}>login
      <Head>
        <title>Pokélove - register</title>
        <meta name="description" content="Generated by a lot of redbull" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Crée un compte
        </h1>

        <a href="./login" className={styles.card}>
          <h2>Déjà inscrit ? &rarr;</h2>
          <p>Ce connecter</p>
        </a>

      </main>
    </div>
  )
}
