import Head from 'next/head'
import styles from '../styles/register.module.css'

const toster = (err) => {
  return (
    <div>
        zrgergerger
    </div>
  )
}

export default function Register() {

  let errors = null

  const registerUser = async event => {
    event.preventDefault()
    const { email, firstname, lastname, password } = event.target
    var formdata = new FormData()
    formdata.append('email',      email.value)
    formdata.append('first_name', firstname.value)
    formdata.append('last_name',  lastname.value)
    formdata.append('password',   password.value)
    console.log(email.value)
    try {
      const res = await globalThis.fetch(
        'http://127.0.0.1:5000/auth/register',
        {
          body: formdata,
          method: 'POST'
        },
      ).then(async r => await r.text())
      console.log('result', res)
      if (res === 'User created successfully') {
        console.log('redirect to login page')
      }
      else
        errors = e
    } catch (e) {
      errors = e
      // throw Error('HOALALAL' + e)
    }
  }

  return (
    <div className={styles.bgPicture}>
      <div className={styles.container}>
        login
        <div>
          {errors? toster(errors) : null}
        </div>
        <Head>
          <title>Pokélove - register</title>
          <meta name="description" content="Generated by a lot of redbull" />
          <link rel="icon" href="/logo.png" />
        </Head>

        <main className={styles.main}>

          <h1 className={styles.title}>
            Crée un compte
          </h1>

          <form onSubmit={registerUser}>

            Email
            <input id="email" name="email"
              type="text" autoComplete="email" required
            />
            <br/>

            Prénom
            <input id="firstname" name="firstname"
              type="text" autoComplete="firstname" required
            />
            <br/>
            Nom de famille
            <input id="lastname" name="lastname"
              type="text" autoComplete="lastname" required
            />
            <br/>
            Mot de passe
            <input id="password" name="password"
              type="password" autoComplete="mot de passe"
              required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
            />
            <br/>
            <button type="submit" className={styles.card}>
              Se connecter
            </button>

          </form>

          <a href="./login" className={styles.card}>
            <h2>Déjà inscrit ? &rarr;</h2>
            <p>Se connecter</p>
          </a>

        </main>
      </div>
    </div>
  )
}
