import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'
import { toast } from 'react-toastify'
import cookieCutter from 'cookie-cutter'

const notify = (txt) => toast(txt)

/** @type {import('./type/userInfo').UserInfo} */
let user

/**
 * @type {{ [key:string]: React.CSSProperties }}
 */
const jsxStyles = {
  mainDiv: {
    border: 'solid',
    borderColor: 'green',
    backgroundColor: 'grey',
    borderRadius: '2rem',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '60vh',
    minWidth: '40vw',
    alignItems: 'center',
    justifyContent: 'space-evenly'
  },
  pictureNameTopRow: {
    fontSize: '5vh',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  profilePicture: {
    borderRadius: '100vh',
    width: '20vh',
    marginRight: '15px',
    position: 'static',
    left: '30%',
  },
  biography: {
    border: 'solid',
    borderColor: 'white',
    backgroundColor: '#ffffff90',
    borderRadius: '2vmin',
    padding: '10px',
    inlineSize: '30vw',
    overflow: 'hidden',
  },
  base: {
    borderRadius:'2vh',
    borderWidth:'0.1vh',
    textAlign:'center',
    paddingInline: '1vmax'
  },
  input: {
    paddingInline: '1vh'
  },
  button: {
    color:'#cacaca',
    padding: '10%'
  }
}


const pushUpdate = (event) => {
  event.preventDefault()
  const { bio, gender } = event.target
  notify(bio.value)
  notify(gender.value)
}


export default function UpdateProfile() {
  /** @type {import('./type/userInfo').UserInfo} */
  let updated
  if (typeof window === "undefined") {
    //bypass ssr
    return null
  } else {
    user = JSON.parse(localStorage.getItem("userInfo"))
    if (!user){
      window.location.href = '/login'
      return null
    } else {
      if (!user.picture) {
        // const session =  localStorage.getItem("session")//cookieCutter.get()
        // document.cookie
        // debugger
        // console.log('session', session)
        fetch('http://127.0.0.1:5000/user/', {
          method: 'GET',
          credentials: 'include'
        }).then((res) => res.json()).then((body) => {
          console.log('body', body)
        })
      }
      console.log(user)
      updated = {...user}
      return (
        <div className={styles.container}>
          <Head>
            <title>Pokélove</title>
            <meta name="description" content="Generated by a lot of redbull" />
            <link rel="icon" href="/logo.png" />
          </Head>
          <form className={styles.main}
            onSubmit={pushUpdate}
          >
            <div style={jsxStyles.mainDiv}>
              <div style={jsxStyles.pictureNameTopRow}>
                <img src='carapuce.jpeg' style={jsxStyles.profilePicture}/>
                {user.username}
              </div>
              popularité
              <textarea id='bio' maxLength={280} rows={6} style={{resize: 'none', ...jsxStyles.biography, ...((!user.short_bio) ? {color: 'grey'} : {color: 'inherit'})}}
                defaultValue={user.short_bio || 'écrire une description ...'}
                onBlur={(event) => {
                  if (event.target.value.length === 0)
                    event.target.value = user.short_bio || 'écrire une description ...'
                }}
              />
              Je suis:
              <select id='gender'>
                <option value='Homme' selected={user.gender === "male"}>Homme</option>
                <option value='Femme' selected={(user.gender === "female")}>Femme</option>
                <option value='Other' selected={user.gender === "other"}>Other</option>
              </select>
              Recherche
              <form id='search' onChange={(event)=>{
                updated[`search_${event.target.value}`] = event.target.checked === true
                console.log(event.target.value, updated[`search_${event.target.value}`])

              }}>
                <label>Homme ♂</label>
                <input type='checkbox' id='male' value='male'/>
                <label>Femme ♀</label>
                <input type='checkbox' id='female' value='female'/>
                <label>Other ⚧</label>
                <input type='checkbox' id='other' value='other'/>
              </form>
              <div>
                tag
              </div>
              <button
                id='magicButton'
                type='submit'
                className={styles.button}
                style={{
                  borderRadius:'2vh',
                  borderWidth:'0.1vh',
                  textAlign:'center',
                  paddingInline: '1vmax',
                  padding: '2vmin',
                }}
              >Sauvgarder</button>
            </div>
          </form>
        </div>
      )
    }
  }
}
