import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { toast } from 'react-toastify'
import Picture from '../components/picture/picture'
import { pushRequest } from './api/apiUtils'
// import cookieCutter from 'cookie-cutter'

const notify = (txt) => toast(txt)

/** @typedef {import('./type/userInfo').UserInfo} UserInfo */
/** @type {UserInfo} */
let localUser

/**
 * @type {{ [key:string]: React.CSSProperties }}
 */
const jsxStyles = {
  mainDiv: {
    border: 'solid',
    backgroundColor: 'grey',
    borderRadius: '2rem',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '60vh',
    minWidth: '40vw',
    alignItems: 'center',
    justifyContent: 'space-evenly'
  },
  pictureNameTopRow: {
    backgroundColor: 'blue',
    fontSize: '5vh',
    flexDirection: 'row',
    alignItems: 'center',
  },
  biography: {
    border: 'solid',
    backgroundColor: '#ffffff90',
    borderRadius: '2vmin',
    padding: '1vmin',
    inlineSize: '29vmax',
    overflow: 'hidden',
  },
  base: {
    borderRadius:'2vh',
    borderWidth:'0.1vh',
    textAlign:'center',
    paddingInline: '1vmax'
  },
  input: {
    paddingInline: '1vh'
  },
  button: {
    color:'#cacaca',
    padding: '10%'
  }
}

export default function UpdateProfile() {

  /** @type {import('./type/userInfo').UserInfo} */
  let userbase = {}
  const pictures = []
  /** @type {[UserInfo, import('react').Dispatch<import('react').SetStateAction<{}>>]} */
  const [user, setUser] = useState(userbase)
  const [tags, setTags] = useState([])
  const [userTags, setUserTags] = useState([])
  const [userPictures, setUserPictures] = useState([])
  const router = useRouter()

  const loadData = async () => {
    //user
    const curUser = await pushRequest('user/', 'GET')
    setUser(curUser)
    localUser = curUser
    localStorage.removeItem("userInfo")
    localStorage.setItem("userInfo", JSON.stringify(curUser))
    //tags
    const tagList = await pushRequest('tag/', 'GET')
    setTags(tagList)
    //user pictures
    const pic = await pushRequest(`user/${curUser.id}/pictures`, 'GET')
    setUserPictures(pic)
  }

  if (typeof window === "undefined") {
    //bypass ssr
    return null
  } else {
    useEffect(async () => {
        await loadData()
      // pushRequest('user/tags/', 'GET')
      //   .then((data) => {
      //     setUserTags(data)
      //   })
      //   .catch((reason) => console.error(reason))
    }, [])
    if (!user){
      localStorage.removeItem("userInfo")
      router.push('/profile')
    }
    const pushUpdate = async (event, userTag) => {
      if (event.key == 'Enter')
        return null
      console.log(event)
      event.preventDefault()
      // const { bio, gender, age, search_female, search_other, search_male } = event.target
      // // notify(bio.value)
      // // notify(search_male.value)
      // const data = new FormData()
      // if (gender && localUser.gender != gender?.value)
      //   data.append("gender", gender?.value)
      // if (age && localUser.age != age?.value)
      //   data.append("age", age?.value)
      // if (search_male && localUser.search_male != search_male?.value)
      //   data.append("search_male", search_male?.value)
      // if (search_female && localUser.search_female != search_female?.value)
      //   data.append("search_female", search_female?.value)
      // if (search_other && localUser.search_other != search_other?.value)
      //   data.append("search_other", search_other?.value)
      // if (bio && localUser.short_bio !== bio?.value)
      //   data.append("short_bio", bio?.value)
      // // if (userTag?.length)
      // //   data.append("tags", userTag)
      // await pushRequest('user/', 'PUT', data)
      // router.push('/profile')
    }

    const renderPicture = userPictures.map((value, index) => (
        <img
          id={'picture'+index}
          style={{display: 'flex'}}
          src={value.picture}
        />
    )) || null
    return (
      <div className={styles.container}>
        <Head>
          <title>Pokélove</title>
          <meta name="description" content="Generated by a lot of redbull" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <form className={styles.main}
          onSubmit={(event) => pushUpdate(event, userTags)}
          id='uno'
        >
          <div style={jsxStyles.mainDiv}>
            <div style={jsxStyles.pictureNameTopRow}>
              <Picture main={true} photo={userPictures} canUpload={true}/>
            </div>
            <textarea form='uno' id='bio' maxLength={280} rows={6} style={{resize: 'none', ...jsxStyles.biography, ...((!user.short_bio) ? {color: 'grey'} : {color:'inherit'})}}
              placeholder={user.short_bio ??= 'écrire une description ...'}
              onBlur={(event) => {
                if (event.target.value.length === 0)
                  event.target.value = user.short_bio || 'écrire une description ...'
              }}
            />
            Je suis:
            <select id='gender' defaultValue={user.gender}>
              <option value='male'>Homme</option>
              <option value='female'>Femme</option>
              <option value='other'>Other</option>
            </select>
            <div>
              {userTags?.map(val => <>{val}&nbsp;</>)}
              <input id='loul' type='text' list='tagsList' placeholder='Ekrivey vö sentre de loizir' size={25}
                onKeyPress={(event) => {
                  if (event.key == 'Enter')
                    if (userTags?.length)
                      setUserTags([...userTags, event.target.value])
                    else
                      setUserTags([event.target.value])
                }}
              />
              <datalist id='tagsList'>
                {tags.map((value) => {
                  return (
                    <option
                      id={"option"+value.name}
                      style={{color: value.color}}
                      value={value.name}
                    >
                      {value.name}
                    </option>
                  )
                })}
              </datalist>
            </div>
            <button
              id='magicButton'
              type='submit'
              className={styles.button}
              form='uno'
              style={{
                borderRadius:'2vh',
                borderWidth:'0.1vh',
                textAlign:'center',
                paddingInline: '1vmax',
                padding: '2vmin',
              }}
            >Sauvgarder</button>
            <div>
              other picture:
              <Picture photo={userPictures} canUpload={true}/>
            </div>
          </div>
        </form>
      </div>
    )
  }
}
